from tkinter import *

def version_window():
    root = Tk()
    root.title('Konwerter rolowań - przegląd uaktualnień wersji')
    scrollbar = Scrollbar(root)
    scrollbar.pack(side=RIGHT, fill=Y)
    textbox = Text(root)
    textbox.pack()
    textbox.insert(END, " * v 0.6\n")
    textbox.insert(END, "     - zmiana OPEN_INT (konwersja dzienna) z 3-1 na 5-2\n")
    textbox.insert(END, "     - dodana konwersja tygodniowa\n")
    textbox.insert(END, "     - zmiany wizualne\n\n\n\n")
    textbox.insert(END, " * v 0.5\n")
    textbox.insert(END, "     - optymalizacja OPEN_INT\n\n\n\n")
    textbox.insert(END, " * v 0.4\n")
    textbox.insert(END, "     - integracja kodu źródłowego z konwerterem kontraktów\n")
    textbox.insert(END, "     - usunięte zbędne zapisy terminala\n")
    textbox.insert(END, "     - dodany wskaźnik postępu w procentach\n")
    textbox.insert(END, "     - optymalizacja kodu\n\n\n\n")
    textbox.insert(END, " * v 0.3\n")
    textbox.insert(END, "     - obsługa konwersji kwartalnej\n")
    textbox.insert(END, "     - dodany progress bar\n")
    textbox.insert(END, "     - naprawione okienko wersji\n\n\n\n")
    textbox.insert(END, " * v 0.2\n")
    textbox.insert(END, "     - obsługa konwersji miesięcznej\n\n\n\n")
    textbox.insert(END, " * v0.1\n")
    textbox.insert(END, "     - obsługa konwersji dziennej open int\n")
    textbox.insert(END, "     - obsługa ściezek plikow i sciezek folderow\n")
    textbox.insert(END, "     - dodany skrypt decydera\n")
    textbox.insert(END, "     - dodany skrypt ekstraktora\n")
    textbox.insert(END, "     - dodany skrypt walidatora\n")
    textbox.insert(END, "     - dodany skrypt stanu\n")
    textbox.insert(END, "     - dodany skrypt normalizacji danych\n")
    textbox.insert(END, "     - obsługa progress baru\n")
    textbox.insert(END, "     - pliki TXT\n")
    textbox.insert(END, "     - pliki CSV\n\n\n\n")


    textbox.config(yscrollcommand=scrollbar.set)
    scrollbar.config(command=textbox.yview)
    root.mainloop()